config/routes.rb
Rails.application.routes.draw do

  resources :todos

  root 'home#index'


end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  def index
    @todo = Todo.new
    @todos = Todo.all
  end

  # POST /todos
  def create
    @todo = Todo.new(todo_params)

    if @todo.save
      redirect_to todos_path, notice: 'Todo was successfully created.'
    else
      render :index
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path, notice: "Todo was successfully deleted"
  end

  private

  def todo_params
    params[:todo].permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1.text-center My App
%br
.row
  .col-xs-12.col-lg-12.col-lg-12
    .text-center
      = link_to "Todo list", todos_path, class: 'btn btn-primary btn-lg'

app/views/layouts/_footer.html.haml
#footer
  .container
    .row.footer-first-row
      .col-xs-12.text-center
        %p
          %small &copy; 2014 - Vedanova

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{class: "alert alert-#{name == "notice" ? "success" : "danger"}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default#navbar
  .navbar-container#navbar-container
    .navbar-header.pull-left
      %button.navbar-toggle{type: "button", data: {toggle:"collapse", target:".navbar-collapse"}}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Todo App', root_path, class: 'navbar-brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Workshop App
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #wrap
      %header
        = render 'layouts/navigation'

      .main-container#main-container
        .row
          .col-lg-6.col-lg-push-3
            = render 'layouts/messages'
            = yield


    = render 'layouts/footer'

app/views/todos/_todo.html.haml
%tr
  %td= todo.name
  %td= l todo.created_at
  %td= link_to 'Delete', todo_path(todo), method: :delete

app/views/todos/index.html.haml
.well.text-center
  %h2 My todos

.row
  %table.table.table-bordered.table-striped#todos
    = render partial: 'todo', collection: @todos

= form_for @todo, class: 'form form-horizontal' do |f|
  = f.label :name, "Add Todo"
  = f.text_field :name, class: 'input-lg'
  = f.submit 'Add todo', class: 'btn btn-primary'